"""Multi-file builds merge all TUs into a single assembly module.

Separate OMF object modules each declare ``group DGROUP data bss``, but NASM
resolves a module's own .bss symbol group-relative (adding that module's .data
size) while alink resolves a cross-module extern reference to the same symbol
.bss-segment-relative (no .data base).  The two disagree by the defining
module's .data size, so a global defined in one TU and used from another lands
at the wrong DGROUP offset.  Merging into one module makes every cross-TU
reference intra-module, eliminating the mismatch.  See builder._merge_asm_modules.
"""

from src.pyc.builder import _merge_asm_modules


def _tu(globals_=(), externs=(), text=(), data=(), bss=(), with_main=False):
    lines = ["; === Generated by pyc ===", "[bits 16]", ""]
    for g in globals_:
        lines.append(f"global {g}")
    if with_main:
        lines.append("global main")
    for e in externs:
        lines.append(f"extern {e}")
    lines.append("section .text")
    lines.extend(text)
    lines.append("section .data")
    if with_main:
        lines.append("_data_start:")
    lines.extend(data)
    lines.append("section .bss")
    lines.extend(bss)
    if with_main:
        lines += ["resb 0x4000", "_stack_top:", "resb 0x400"]
        lines += ["section .stack stack class=STACK", "resb 0x10"]
    lines.append("group DGROUP data bss")
    return "\n".join(lines)


def test_merge_produces_single_module_with_one_dgroup() -> None:
    tu0 = _tu(globals_=("numRooms",), text=["GenLevel:", "ret"], bss=["numRooms: resw 1"])
    tu1 = _tu(externs=("numRooms",), text=["main:", "call GenLevel", "ret"], with_main=True)
    merged = _merge_asm_modules([tu0, tu1])

    # Exactly one of each structural element.
    assert merged.count("group DGROUP data bss") == 1
    assert merged.count("_data_start:") == 1
    assert merged.count("_stack_top:") == 1
    assert merged.count("section .text") == 1
    # Entry bootstrap is emitted once.
    assert merged.count("_entry:") == 1
    assert "call main" in merged


def test_extern_satisfied_internally_is_dropped() -> None:
    tu0 = _tu(globals_=("numRooms",), bss=["numRooms: resw 1"])
    tu1 = _tu(externs=("numRooms", "printf"), with_main=True)
    merged = _merge_asm_modules([tu0, tu1])
    # numRooms is defined in the merged module — must not also be `extern`.
    assert "extern numRooms" not in merged
    assert "global numRooms" in merged
    # A genuinely external symbol stays external.
    assert "extern printf" in merged


def test_per_tu_string_labels_are_disambiguated() -> None:
    # Both TUs number their string literals from _str_1; the merge must keep
    # them distinct so they don't collide as duplicate labels.
    tu0 = _tu(data=['_str_1 db "a", 0'], text=["f:", "mov ax, _str_1", "ret"])
    tu1 = _tu(data=['_str_1 db "b", 0'], text=["g:", "mov ax, _str_1", "ret"],
              with_main=True)
    merged = _merge_asm_modules([tu0, tu1])
    assert '_str_0_1 db "a", 0' in merged
    assert '_str_1_1 db "b", 0' in merged
    # References renamed consistently with their definitions.
    assert "mov ax, _str_0_1" in merged
    assert "mov ax, _str_1_1" in merged


def test_get_stdlib_objects_exclude_drops_module() -> None:
    """exclude=['fp'] omits the soft-float runtime so a float-free program can
    stay under alink's 32 KB near-call limit (see builder.link)."""
    from src.pyc.builder import get_stdlib_objects

    full = {p.stem for p in get_stdlib_objects()}
    without_fp = {p.stem for p in get_stdlib_objects(exclude=["fp"])}
    assert "fp" in full
    assert "fp" not in without_fp
    # everything else is unchanged.
    assert full - {"fp"} == without_fp
