; === Generated by pyc ===

[bits 16]


; --- Exported symbols ---
global _entry
global main

; --- Imported symbols ---
extern fprintf
extern getchar
extern printf
extern putchar
extern puts
extern sprintf
extern stderr
extern stdin
extern stdout

; --- Code Segment ---
section .text

main:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
mov ax, _str_1
push ax
call printf
add sp, 2
mov ax, 0
.main_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_entry:
mov ax, seg _data_start
mov ds, ax
mov es, ax
cli
mov ss, ax
mov sp, _stack_top
sti
sub sp, 16
xor ax, ax
push ax
mov ax, 1
push ax
call main
add sp, 4
add sp, 16
mov ah, 0x4C
int 0x21

; --- Data Segment ---
section .data

_data_start:
_str_1 db "Hello, World!", 10, 0

; --- BSS Segment ---
section .bss

resb 0x4000
_stack_top:
resb 0x400

; --- Stack Segment ---
section .stack stack class=STACK
resb 0x10

group DGROUP data bss