; === Generated by pyc ===

[bits 16]


; --- Exported symbols ---
global _emit_char
global _emit_string
global _print_double_prec
global _print_double_words
global _print_hex
global _print_hex_long
global _print_int
global _print_uint
global _spr_emit_char
global _spr_emit_string
global _spr_n
global _spr_out
global _spr_print_int
global _spr_print_uint
global fprintf
global getchar
global printf
global putchar
global puts
global scanf
global sprintf
global stderr
global stdin
global stdout

; --- Imported symbols ---
extern __print_d64
extern _getchar
extern _print
extern _print_llong
extern _print_long
extern _print_ullong
extern _print_ulong
extern _putchar
extern _readline

; --- Code Segment ---
section .text

_emit_char:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; stdio.c - Standard I/O library for pyc
; DOS I/O helper declarations
; --- printf ---
; Minimal printf: supports %d (decimal int), %s (string), %% (literal %)
mov ax, [bp + 4]
push ax
call _putchar
add sp, 2
._emit_char_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_emit_string:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
.Lwhile_1:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_2
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _putchar
add sp, 2
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_1
.Lwhileend_2:
._emit_string_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_uint:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 6
; Convert integer to decimal string
mov ax, 10000
mov [bp + -12], ax
mov ax, 0
mov [bp + -14], ax
.Lwhile_3:
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_5
mov ax, 0
jmp .Lcmpend_6
.Lcmp_5:
mov ax, 1
.Lcmpend_6:
test ax, ax
jz .Lwhileend_4
mov ax, [bp + 4]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -16], ax
mov ax, [bp + 4]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
xor dx, dx
div bx
mov ax, dx
mov [bp + 4], ax
mov ax, [bp + -16]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_11
mov ax, 0
jmp .Lcmpend_12
.Lcmp_11:
mov ax, 1
.Lcmpend_12:
test ax, ax
jnz .Lsctrue_13
mov ax, [bp + -14]
test ax, ax
jnz .Lsctrue_13
mov ax, 0
jmp .Lscend_10
.Lsctrue_13:
mov ax, 1
.Lscend_10:
test ax, ax
jnz .Lsctrue_14
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_15
mov ax, 0
jmp .Lcmpend_16
.Lcmp_15:
mov ax, 1
.Lcmpend_16:
test ax, ax
jnz .Lsctrue_14
mov ax, 0
jmp .Lscend_9
.Lsctrue_14:
mov ax, 1
.Lscend_9:
test ax, ax
jz .Lelse_7
mov ax, [bp + -16]
push ax
mov ax, 48
mov bx, ax
pop ax
add ax, bx
push ax
call _emit_char
add sp, 2
mov ax, 1
mov [bp + -14], ax
jmp .Lendif_8
.Lelse_7:
.Lendif_8:
mov ax, [bp + -12]
push ax
mov ax, 10
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -12], ax
jmp .Lwhile_3
.Lwhileend_4:
._print_uint_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_int:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 8
; Print the absolute value via UNSIGNED division so that the
; INT_MIN case (where `-INT_MIN` overflows back to INT_MIN in two's
; complement) still produces a positive divisor.  Bit-pattern
; negate is equivalent to two's complement: in 16 bits, -INT_MIN
; has the bit pattern 0x8000, which when read unsigned is 32768 —
; exactly |INT_MIN|.
mov ax, [bp + 4]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_19
mov ax, 0
jmp .Lcmpend_20
.Lcmp_19:
mov ax, 1
.Lcmpend_20:
test ax, ax
jz .Lelse_17
mov ax, 45
push ax
call _emit_char
add sp, 2
mov ax, [bp + 4]
neg ax
mov [bp + 4], ax
jmp .Lendif_18
.Lelse_17:
.Lendif_18:
mov ax, [bp + 4]
mov [bp + -12], ax
mov ax, 10000
mov [bp + -14], ax
mov ax, 0
mov [bp + -16], ax
.Lwhile_21:
mov ax, [bp + -14]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_23
mov ax, 0
jmp .Lcmpend_24
.Lcmp_23:
mov ax, 1
.Lcmpend_24:
test ax, ax
jz .Lwhileend_22
mov ax, [bp + -12]
push ax
mov ax, [bp + -14]
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -18], ax
mov ax, [bp + -12]
push ax
mov ax, [bp + -14]
mov bx, ax
pop ax
xor dx, dx
div bx
mov ax, dx
mov [bp + -12], ax
mov ax, [bp + -18]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_29
mov ax, 0
jmp .Lcmpend_30
.Lcmp_29:
mov ax, 1
.Lcmpend_30:
test ax, ax
jnz .Lsctrue_31
mov ax, [bp + -16]
test ax, ax
jnz .Lsctrue_31
mov ax, 0
jmp .Lscend_28
.Lsctrue_31:
mov ax, 1
.Lscend_28:
test ax, ax
jnz .Lsctrue_32
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_33
mov ax, 0
jmp .Lcmpend_34
.Lcmp_33:
mov ax, 1
.Lcmpend_34:
test ax, ax
jnz .Lsctrue_32
mov ax, 0
jmp .Lscend_27
.Lsctrue_32:
mov ax, 1
.Lscend_27:
test ax, ax
jz .Lelse_25
mov ax, [bp + -18]
push ax
mov ax, 48
mov bx, ax
pop ax
add ax, bx
push ax
call _emit_char
add sp, 2
mov ax, 1
mov [bp + -16], ax
jmp .Lendif_26
.Lelse_25:
.Lendif_26:
mov ax, [bp + -14]
push ax
mov ax, 10
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -14], ax
jmp .Lwhile_21
.Lwhileend_22:
._print_int_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_hex:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 12
; Emit `u` in hex.  No width or zero-padding — the caller's format
; string controls that (we don't parse width specs yet).
mov ax, 0
mov [bp + -20], ax
mov ax, [bp + 4]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_37
mov ax, 0
jmp .Lcmpend_38
.Lcmp_37:
mov ax, 1
.Lcmpend_38:
test ax, ax
jz .Lelse_35
mov ax, 48
push ax
call _emit_char
add sp, 2
jmp ._print_hex_ret
jmp .Lendif_36
.Lelse_35:
.Lendif_36:
.Lwhile_39:
mov ax, [bp + 4]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_41
mov ax, 0
jmp .Lcmpend_42
.Lcmp_41:
mov ax, 1
.Lcmpend_42:
test ax, ax
jz .Lwhileend_40
mov ax, [bp + 4]
push ax
mov ax, 15
mov bx, ax
pop ax
and ax, bx
mov [bp + -22], ax
mov ax, [bp + -22]
push ax
mov ax, 10
mov bx, ax
pop ax
cmp ax, bx
jb .Lcmp_45
mov ax, 0
jmp .Lcmpend_46
.Lcmp_45:
mov ax, 1
.Lcmpend_46:
test ax, ax
jz .Lelse_43
mov ax, [bp + -22]
push ax
mov ax, 48
mov bx, ax
pop ax
add ax, bx
push ax
lea ax, [bp + -18]
push ax
mov ax, [bp + -20]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
jmp .Lendif_44
.Lelse_43:
mov ax, [bp + -22]
push ax
mov ax, 10
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 97
mov bx, ax
pop ax
add ax, bx
push ax
lea ax, [bp + -18]
push ax
mov ax, [bp + -20]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
.Lendif_44:
mov ax, [bp + 4]
push ax
mov ax, 4
mov bx, ax
pop ax
mov cl, bl
shr ax, cl
mov [bp + 4], ax
mov ax, [bp + -20]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -20], ax
jmp .Lwhile_39
.Lwhileend_40:
.Lwhile_47:
mov ax, [bp + -20]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_49
mov ax, 0
jmp .Lcmpend_50
.Lcmp_49:
mov ax, 1
.Lcmpend_50:
test ax, ax
jz .Lwhileend_48
mov ax, [bp + -20]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + -20], ax
lea ax, [bp + -18]
push ax
mov ax, [bp + -20]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _emit_char
add sp, 2
jmp .Lwhile_47
.Lwhileend_48:
._print_hex_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_hex_long:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 16
mov ax, [bp + 6]
mov [bp + -12], ax
mov ax, [bp + 4]
mov [bp + -14], ax
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_53
mov ax, 0
jmp .Lcmpend_54
.Lcmp_53:
mov ax, 1
.Lcmpend_54:
test ax, ax
jz .Lelse_51
mov ax, [bp + -12]
push ax
call _print_hex
add sp, 2
; Pad low half to 4 hex digits.
mov ax, 0
mov [bp + -20], ax
mov ax, [bp + -14]
mov [bp + -22], ax
mov ax, 0
mov [bp + -24], ax
.Lfor_55:
mov ax, [bp + -24]
push ax
mov ax, 4
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_58
mov ax, 0
jmp .Lcmpend_59
.Lcmp_58:
mov ax, 1
.Lcmpend_59:
test ax, ax
jz .Lforend_57
mov ax, [bp + -22]
push ax
mov ax, 15
mov bx, ax
pop ax
and ax, bx
mov [bp + -26], ax
mov ax, [bp + -26]
push ax
mov ax, 10
mov bx, ax
pop ax
cmp ax, bx
jb .Lcmp_62
mov ax, 0
jmp .Lcmpend_63
.Lcmp_62:
mov ax, 1
.Lcmpend_63:
test ax, ax
jz .Lelse_60
mov ax, [bp + -26]
push ax
mov ax, 48
mov bx, ax
pop ax
add ax, bx
push ax
lea ax, [bp + -18]
push ax
mov ax, [bp + -24]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
jmp .Lendif_61
.Lelse_60:
mov ax, [bp + -26]
push ax
mov ax, 10
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 97
mov bx, ax
pop ax
add ax, bx
push ax
lea ax, [bp + -18]
push ax
mov ax, [bp + -24]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
.Lendif_61:
mov ax, [bp + -22]
push ax
mov ax, 4
mov bx, ax
pop ax
mov cl, bl
shr ax, cl
mov [bp + -22], ax
.Lforcontinue_56:
mov ax, [bp + -24]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -24], ax
jmp .Lfor_55
.Lforend_57:
mov ax, 3
mov [bp + -24], ax
.Lfor_64:
mov ax, [bp + -24]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jge .Lcmp_67
mov ax, 0
jmp .Lcmpend_68
.Lcmp_67:
mov ax, 1
.Lcmpend_68:
test ax, ax
jz .Lforend_66
lea ax, [bp + -18]
push ax
mov ax, [bp + -24]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _emit_char
add sp, 2
.Lforcontinue_65:
mov ax, [bp + -24]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + -24], ax
jmp .Lfor_64
.Lforend_66:
jmp .Lendif_52
.Lelse_51:
mov ax, [bp + -14]
push ax
call _print_hex
add sp, 2
.Lendif_52:
._print_hex_long_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
printf:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 44
; Variadic printf: supports
; %d, %i        signed int (decimal)
; %u            unsigned int (decimal)
; %ld, %li      signed long (32-bit decimal)
; %lu           unsigned long (32-bit decimal)
; %s            null-terminated string
; %%            literal '%'
; 16-bit args consume one va_list slot (advancing `ap` by one int).
; 32-bit args consume two slots; we manually read the low/high words
; and pass them to _print_long/_print_ulong, which expect a long on the
; stack (cdecl: low at [bp+4], high at [bp+6]).
; Advance `ap` by enough int-sized slots to cover `sizeof(type)` bytes,
; then dereference the previous location as the requested type.  Works
; for any type whose size is a multiple of sizeof(int) (16-bit int, so
; unsigned long → 2 slots, char → still 1 slot per default promotion).
; The 32-bit print helpers live in long_io.asm.  Declaring them as
; `(int low, int high)` lines the cdecl call layout up with the helper
; body, which reads low at [bp+4] and high at [bp+6] — the same
; layout a `long` argument would produce.
mov ax, [bp + 4]
lea ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 4]
mov [bp + -14], ax
.Lwhile_69:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_70
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_73
mov ax, 0
jmp .Lcmpend_74
.Lcmp_73:
mov ax, 1
.Lcmpend_74:
test ax, ax
jz .Lelse_71
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, 1
neg ax
mov [bp + -16], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 46
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_77
mov ax, 0
jmp .Lcmpend_78
.Lcmp_77:
mov ax, 1
.Lcmpend_78:
test ax, ax
jz .Lelse_75
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, 0
mov [bp + -16], ax
.Lwhile_79:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
cmp ax, bx
jge .Lcmp_82
mov ax, 0
jmp .Lcmpend_83
.Lcmp_82:
mov ax, 1
.Lcmpend_83:
test ax, ax
jz .Lscend_81
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 57
mov bx, ax
pop ax
cmp ax, bx
jle .Lcmp_84
mov ax, 0
jmp .Lcmpend_85
.Lcmp_84:
mov ax, 1
.Lcmpend_85:
test ax, ax
jnz .Lsctrue_86
mov ax, 0
jmp .Lscend_81
.Lsctrue_86:
mov ax, 1
.Lscend_81:
test ax, ax
jz .Lwhileend_80
mov ax, [bp + -16]
push ax
mov ax, 10
mov bx, ax
pop ax
imul bx
push ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
sub ax, bx
mov bx, ax
pop ax
add ax, bx
mov [bp + -16], ax
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lwhile_79
.Lwhileend_80:
jmp .Lendif_76
.Lelse_75:
.Lendif_76:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 76
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_89
mov ax, 0
jmp .Lcmpend_90
.Lcmp_89:
mov ax, 1
.Lcmpend_90:
test ax, ax
jz .Lelse_87
; `%Lf` — long double formatting.  Our long double is
; aliased to double; treat the same as `%f` (4-word
; double argument).
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -18], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -20], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -22], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -24], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -16]
push ax
mov ax, [bp + -24]
push ax
mov ax, [bp + -22]
push ax
mov ax, [bp + -20]
push ax
mov ax, [bp + -18]
push ax
call _print_double_prec
add sp, 10
jmp .Lendif_88
.Lelse_87:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 108
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_93
mov ax, 0
jmp .Lcmpend_94
.Lcmp_93:
mov ax, 1
.Lcmpend_94:
test ax, ax
jz .Lelse_91
; Long-modifier prefix: %ld / %li / %lu / %lx.  Pull
; the two word slots that make up the 32-bit value.
; For %lld / %llu / %llx (long long), advance over the
; second 'l' and consume two extra words; we only print
; the low 32 bits via the same helpers — sufficient
; for values that fit in 32 bits.
; For `%lf` — long form of %f — read a 4-word double.
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, 0
mov [bp + -26], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 108
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_97
mov ax, 0
jmp .Lcmpend_98
.Lcmp_97:
mov ax, 1
.Lcmpend_98:
test ax, ax
jz .Lelse_95
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, 1
mov [bp + -26], ax
jmp .Lendif_96
.Lelse_95:
.Lendif_96:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 102
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_101
mov ax, 0
jmp .Lcmpend_102
.Lcmp_101:
mov ax, 1
.Lcmpend_102:
test ax, ax
jz .Lelse_99
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -28], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -30], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -32], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -34], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -16]
push ax
mov ax, [bp + -34]
push ax
mov ax, [bp + -32]
push ax
mov ax, [bp + -30]
push ax
mov ax, [bp + -28]
push ax
call _print_double_prec
add sp, 10
jmp .Lendif_100
.Lelse_99:
mov ax, [bp + -26]
test ax, ax
jz .Lelse_103
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -36], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -38], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -40], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -42], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 100
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_108
mov ax, 0
jmp .Lcmpend_109
.Lcmp_108:
mov ax, 1
.Lcmpend_109:
test ax, ax
jnz .Lsctrue_110
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 105
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_111
mov ax, 0
jmp .Lcmpend_112
.Lcmp_111:
mov ax, 1
.Lcmpend_112:
test ax, ax
jnz .Lsctrue_110
mov ax, 0
jmp .Lscend_107
.Lsctrue_110:
mov ax, 1
.Lscend_107:
test ax, ax
jz .Lelse_105
mov ax, [bp + -42]
push ax
mov ax, [bp + -40]
push ax
mov ax, [bp + -38]
push ax
mov ax, [bp + -36]
push ax
call _print_llong
add sp, 8
jmp .Lendif_106
.Lelse_105:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 117
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_115
mov ax, 0
jmp .Lcmpend_116
.Lcmp_115:
mov ax, 1
.Lcmpend_116:
test ax, ax
jz .Lelse_113
mov ax, [bp + -42]
push ax
mov ax, [bp + -40]
push ax
mov ax, [bp + -38]
push ax
mov ax, [bp + -36]
push ax
call _print_ullong
add sp, 8
jmp .Lendif_114
.Lelse_113:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 120
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_120
mov ax, 0
jmp .Lcmpend_121
.Lcmp_120:
mov ax, 1
.Lcmpend_121:
test ax, ax
jnz .Lsctrue_122
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 88
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_123
mov ax, 0
jmp .Lcmpend_124
.Lcmp_123:
mov ax, 1
.Lcmpend_124:
test ax, ax
jnz .Lsctrue_122
mov ax, 0
jmp .Lscend_119
.Lsctrue_122:
mov ax, 1
.Lscend_119:
test ax, ax
jz .Lelse_117
; No dedicated 64-bit hex helper yet; fall back to
; the low 32 bits.
mov ax, [bp + -38]
push ax
mov ax, [bp + -36]
push ax
call _print_hex_long
add sp, 4
jmp .Lendif_118
.Lelse_117:
.Lendif_118:
.Lendif_114:
.Lendif_106:
jmp .Lendif_104
.Lelse_103:
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -44], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -46], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 100
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_128
mov ax, 0
jmp .Lcmpend_129
.Lcmp_128:
mov ax, 1
.Lcmpend_129:
test ax, ax
jnz .Lsctrue_130
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 105
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_131
mov ax, 0
jmp .Lcmpend_132
.Lcmp_131:
mov ax, 1
.Lcmpend_132:
test ax, ax
jnz .Lsctrue_130
mov ax, 0
jmp .Lscend_127
.Lsctrue_130:
mov ax, 1
.Lscend_127:
test ax, ax
jz .Lelse_125
mov ax, [bp + -46]
push ax
mov ax, [bp + -44]
push ax
call _print_long
add sp, 4
jmp .Lendif_126
.Lelse_125:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 117
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_135
mov ax, 0
jmp .Lcmpend_136
.Lcmp_135:
mov ax, 1
.Lcmpend_136:
test ax, ax
jz .Lelse_133
mov ax, [bp + -46]
push ax
mov ax, [bp + -44]
push ax
call _print_ulong
add sp, 4
jmp .Lendif_134
.Lelse_133:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 120
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_140
mov ax, 0
jmp .Lcmpend_141
.Lcmp_140:
mov ax, 1
.Lcmpend_141:
test ax, ax
jnz .Lsctrue_142
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 88
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_143
mov ax, 0
jmp .Lcmpend_144
.Lcmp_143:
mov ax, 1
.Lcmpend_144:
test ax, ax
jnz .Lsctrue_142
mov ax, 0
jmp .Lscend_139
.Lsctrue_142:
mov ax, 1
.Lscend_139:
test ax, ax
jz .Lelse_137
mov ax, [bp + -46]
push ax
mov ax, [bp + -44]
push ax
call _print_hex_long
add sp, 4
jmp .Lendif_138
.Lelse_137:
.Lendif_138:
.Lendif_134:
.Lendif_126:
.Lendif_104:
.Lendif_100:
jmp .Lendif_92
.Lelse_91:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 100
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_148
mov ax, 0
jmp .Lcmpend_149
.Lcmp_148:
mov ax, 1
.Lcmpend_149:
test ax, ax
jnz .Lsctrue_150
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 105
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_151
mov ax, 0
jmp .Lcmpend_152
.Lcmp_151:
mov ax, 1
.Lcmpend_152:
test ax, ax
jnz .Lsctrue_150
mov ax, 0
jmp .Lscend_147
.Lsctrue_150:
mov ax, 1
.Lscend_147:
test ax, ax
jz .Lelse_145
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_int
add sp, 2
jmp .Lendif_146
.Lelse_145:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 117
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_155
mov ax, 0
jmp .Lcmpend_156
.Lcmp_155:
mov ax, 1
.Lcmpend_156:
test ax, ax
jz .Lelse_153
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_uint
add sp, 2
jmp .Lendif_154
.Lelse_153:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 120
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_160
mov ax, 0
jmp .Lcmpend_161
.Lcmp_160:
mov ax, 1
.Lcmpend_161:
test ax, ax
jnz .Lsctrue_162
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 88
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_163
mov ax, 0
jmp .Lcmpend_164
.Lcmp_163:
mov ax, 1
.Lcmpend_164:
test ax, ax
jnz .Lsctrue_162
mov ax, 0
jmp .Lscend_159
.Lsctrue_162:
mov ax, 1
.Lscend_159:
test ax, ax
jz .Lelse_157
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_hex
add sp, 2
jmp .Lendif_158
.Lelse_157:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 112
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_167
mov ax, 0
jmp .Lcmpend_168
.Lcmp_167:
mov ax, 1
.Lcmpend_168:
test ax, ax
jz .Lelse_165
; Near pointer: 16-bit hex.
mov ax, 48
push ax
call _emit_char
add sp, 2
mov ax, 120
push ax
call _emit_char
add sp, 2
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_hex
add sp, 2
jmp .Lendif_166
.Lelse_165:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 99
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_171
mov ax, 0
jmp .Lcmpend_172
.Lcmp_171:
mov ax, 1
.Lcmpend_172:
test ax, ax
jz .Lelse_169
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _emit_char
add sp, 2
jmp .Lendif_170
.Lelse_169:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 102
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_175
mov ax, 0
jmp .Lcmpend_176
.Lcmp_175:
mov ax, 1
.Lcmpend_176:
test ax, ax
jz .Lelse_173
; %f — 64-bit double in cdecl arg slot.  Pull 4 words.
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -48], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -50], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -52], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
mov bx, ax
mov ax, [bx]
mov [bp + -54], ax
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -16]
push ax
mov ax, [bp + -54]
push ax
mov ax, [bp + -52]
push ax
mov ax, [bp + -50]
push ax
mov ax, [bp + -48]
push ax
call _print_double_prec
add sp, 10
jmp .Lendif_174
.Lelse_173:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 115
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_179
mov ax, 0
jmp .Lcmpend_180
.Lcmp_179:
mov ax, 1
.Lcmpend_180:
test ax, ax
jz .Lelse_177
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _emit_string
add sp, 2
jmp .Lendif_178
.Lelse_177:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_183
mov ax, 0
jmp .Lcmpend_184
.Lcmp_183:
mov ax, 1
.Lcmpend_184:
test ax, ax
jz .Lelse_181
mov ax, 37
push ax
call _emit_char
add sp, 2
jmp .Lendif_182
.Lelse_181:
.Lendif_182:
.Lendif_178:
.Lendif_174:
.Lendif_170:
.Lendif_166:
.Lendif_158:
.Lendif_154:
.Lendif_146:
.Lendif_92:
.Lendif_88:
jmp .Lendif_72
.Lelse_71:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _emit_char
add sp, 2
.Lendif_72:
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lwhile_69
.Lwhileend_70:
mov ax, 0
jmp .printf_ret
.printf_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_double_words:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- sprintf ---
; Minimal sprintf: same format support as printf, writes to a buffer.
; The buffer must be large enough — no bounds checking.
; External: floating-point printer from `stdlib/fp.asm`.  Reads the
; four 16-bit words of the double off the cdecl-style argument frame
; ([bp+4..+10]) plus a precision word at [bp+12], and emits via
; `_putchar`.  precision: number of fractional digits (-1 = default 6).
mov ax, 1
neg ax
push ax
mov ax, [bp + 10]
push ax
mov ax, [bp + 8]
push ax
mov ax, [bp + 6]
push ax
mov ax, [bp + 4]
push ax
call __print_d64
add sp, 10
._print_double_words_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_print_double_prec:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
mov ax, [bp + 12]
push ax
mov ax, [bp + 10]
push ax
mov ax, [bp + 8]
push ax
mov ax, [bp + 6]
push ax
mov ax, [bp + 4]
push ax
call __print_d64
add sp, 10
._print_double_prec_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_spr_emit_char:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; running count of chars emitted by _spr_emit_char
mov ax, [bp + 4]
push ax
mov ax, [_spr_out]
mov bx, ax
pop ax
mov [bx], al
mov ax, [_spr_out]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [_spr_out], ax
mov ax, [_spr_n]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [_spr_n], ax
._spr_emit_char_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_spr_emit_string:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
.Lwhile_185:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_186
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _spr_emit_char
add sp, 2
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_185
.Lwhileend_186:
._spr_emit_string_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_spr_print_uint:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 6
mov ax, 10000
mov [bp + -12], ax
mov ax, 0
mov [bp + -14], ax
.Lwhile_187:
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_189
mov ax, 0
jmp .Lcmpend_190
.Lcmp_189:
mov ax, 1
.Lcmpend_190:
test ax, ax
jz .Lwhileend_188
mov ax, [bp + 4]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -16], ax
mov ax, [bp + 4]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
xor dx, dx
div bx
mov ax, dx
mov [bp + 4], ax
mov ax, [bp + -16]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
ja .Lcmp_195
mov ax, 0
jmp .Lcmpend_196
.Lcmp_195:
mov ax, 1
.Lcmpend_196:
test ax, ax
jnz .Lsctrue_197
mov ax, [bp + -14]
test ax, ax
jnz .Lsctrue_197
mov ax, 0
jmp .Lscend_194
.Lsctrue_197:
mov ax, 1
.Lscend_194:
test ax, ax
jnz .Lsctrue_198
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_199
mov ax, 0
jmp .Lcmpend_200
.Lcmp_199:
mov ax, 1
.Lcmpend_200:
test ax, ax
jnz .Lsctrue_198
mov ax, 0
jmp .Lscend_193
.Lsctrue_198:
mov ax, 1
.Lscend_193:
test ax, ax
jz .Lelse_191
mov ax, [bp + -16]
push ax
mov ax, 48
mov bx, ax
pop ax
add ax, bx
push ax
call _spr_emit_char
add sp, 2
mov ax, 1
mov [bp + -14], ax
jmp .Lendif_192
.Lelse_191:
.Lendif_192:
mov ax, [bp + -12]
push ax
mov ax, 10
mov bx, ax
pop ax
xor dx, dx
div bx
mov [bp + -12], ax
jmp .Lwhile_187
.Lwhileend_188:
._spr_print_uint_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
_spr_print_int:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
mov ax, [bp + 4]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_203
mov ax, 0
jmp .Lcmpend_204
.Lcmp_203:
mov ax, 1
.Lcmpend_204:
test ax, ax
jz .Lelse_201
mov ax, 45
push ax
call _spr_emit_char
add sp, 2
mov ax, [bp + 4]
neg ax
mov [bp + 4], ax
jmp .Lendif_202
.Lelse_201:
.Lendif_202:
mov ax, [bp + 4]
push ax
call _spr_print_uint
add sp, 2
._spr_print_int_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
sprintf:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 12
mov ax, [bp + 6]
lea ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 4]
mov [_spr_out], ax
mov ax, [bp + 6]
mov [bp + -14], ax
.Lwhile_205:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_206
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_209
mov ax, 0
jmp .Lcmpend_210
.Lcmp_209:
mov ax, 1
.Lcmpend_210:
test ax, ax
jz .Lelse_207
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
; Parse optional '-' flag (left-justify).
mov ax, 0
mov [bp + -16], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 45
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_213
mov ax, 0
jmp .Lcmpend_214
.Lcmp_213:
mov ax, 1
.Lcmpend_214:
test ax, ax
jz .Lelse_211
mov ax, 1
mov [bp + -16], ax
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lendif_212
.Lelse_211:
.Lendif_212:
; Parse optional minimum field width.
mov ax, 0
mov [bp + -18], ax
.Lwhile_215:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
cmp ax, bx
jge .Lcmp_218
mov ax, 0
jmp .Lcmpend_219
.Lcmp_218:
mov ax, 1
.Lcmpend_219:
test ax, ax
jz .Lscend_217
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 57
mov bx, ax
pop ax
cmp ax, bx
jle .Lcmp_220
mov ax, 0
jmp .Lcmpend_221
.Lcmp_220:
mov ax, 1
.Lcmpend_221:
test ax, ax
jnz .Lsctrue_222
mov ax, 0
jmp .Lscend_217
.Lsctrue_222:
mov ax, 1
.Lscend_217:
test ax, ax
jz .Lwhileend_216
mov ax, [bp + -18]
push ax
mov ax, 10
mov bx, ax
pop ax
imul bx
push ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
sub ax, bx
mov bx, ax
pop ax
add ax, bx
mov [bp + -18], ax
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lwhile_215
.Lwhileend_216:
; Snapshot char counter; after emit, measure how many were written.
mov ax, [_spr_n]
mov [bp + -20], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 100
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_226
mov ax, 0
jmp .Lcmpend_227
.Lcmp_226:
mov ax, 1
.Lcmpend_227:
test ax, ax
jnz .Lsctrue_228
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 105
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_229
mov ax, 0
jmp .Lcmpend_230
.Lcmp_229:
mov ax, 1
.Lcmpend_230:
test ax, ax
jnz .Lsctrue_228
mov ax, 0
jmp .Lscend_225
.Lsctrue_228:
mov ax, 1
.Lscend_225:
test ax, ax
jz .Lelse_223
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _spr_print_int
add sp, 2
jmp .Lendif_224
.Lelse_223:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 117
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_233
mov ax, 0
jmp .Lcmpend_234
.Lcmp_233:
mov ax, 1
.Lcmpend_234:
test ax, ax
jz .Lelse_231
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _spr_print_uint
add sp, 2
jmp .Lendif_232
.Lelse_231:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 115
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_237
mov ax, 0
jmp .Lcmpend_238
.Lcmp_237:
mov ax, 1
.Lcmpend_238:
test ax, ax
jz .Lelse_235
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _spr_emit_string
add sp, 2
jmp .Lendif_236
.Lelse_235:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 99
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_241
mov ax, 0
jmp .Lcmpend_242
.Lcmp_241:
mov ax, 1
.Lcmpend_242:
test ax, ax
jz .Lelse_239
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _spr_emit_char
add sp, 2
jmp .Lendif_240
.Lelse_239:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_245
mov ax, 0
jmp .Lcmpend_246
.Lcmp_245:
mov ax, 1
.Lcmpend_246:
test ax, ax
jz .Lelse_243
mov ax, 37
push ax
call _spr_emit_char
add sp, 2
jmp .Lendif_244
.Lelse_243:
.Lendif_244:
.Lendif_240:
.Lendif_236:
.Lendif_232:
.Lendif_224:
; Left-justify: pad with trailing spaces to reach width.
mov ax, [bp + -16]
test ax, ax
jz .Lscend_249
mov ax, [bp + -18]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_250
mov ax, 0
jmp .Lcmpend_251
.Lcmp_250:
mov ax, 1
.Lcmpend_251:
test ax, ax
jnz .Lsctrue_252
mov ax, 0
jmp .Lscend_249
.Lsctrue_252:
mov ax, 1
.Lscend_249:
test ax, ax
jz .Lelse_247
mov ax, [_spr_n]
push ax
mov ax, [bp + -20]
mov bx, ax
pop ax
sub ax, bx
mov [bp + -22], ax
.Lwhile_253:
mov ax, [bp + -22]
push ax
mov ax, [bp + -18]
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_255
mov ax, 0
jmp .Lcmpend_256
.Lcmp_255:
mov ax, 1
.Lcmpend_256:
test ax, ax
jz .Lwhileend_254
mov ax, 32
push ax
call _spr_emit_char
add sp, 2
mov ax, [bp + -22]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -22], ax
jmp .Lwhile_253
.Lwhileend_254:
jmp .Lendif_248
.Lelse_247:
.Lendif_248:
jmp .Lendif_208
.Lelse_207:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _spr_emit_char
add sp, 2
.Lendif_208:
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lwhile_205
.Lwhileend_206:
mov ax, 0
push ax
mov ax, [_spr_out]
mov bx, ax
pop ax
mov [bx], al
mov ax, 0
jmp .sprintf_ret
.sprintf_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
fprintf:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 4
; --- fprintf: minimal implementation, ignores stream and writes to stdout.
; This compiler has no real FILE* — `stderr` is just an opaque pointer.
; TODO: route to a real stream.  For now reuse the printf logic by
; formatting into a buffer and emitting.
mov ax, [bp + 6]
lea ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
shl bx, 1
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 6]
mov [bp + -14], ax
.Lwhile_257:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_258
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_261
mov ax, 0
jmp .Lcmpend_262
.Lcmp_261:
mov ax, 1
.Lcmpend_262:
test ax, ax
jz .Lelse_259
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 100
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_266
mov ax, 0
jmp .Lcmpend_267
.Lcmp_266:
mov ax, 1
.Lcmpend_267:
test ax, ax
jnz .Lsctrue_268
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 105
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_269
mov ax, 0
jmp .Lcmpend_270
.Lcmp_269:
mov ax, 1
.Lcmpend_270:
test ax, ax
jnz .Lsctrue_268
mov ax, 0
jmp .Lscend_265
.Lsctrue_268:
mov ax, 1
.Lscend_265:
test ax, ax
jz .Lelse_263
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_int
add sp, 2
jmp .Lendif_264
.Lelse_263:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 117
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_273
mov ax, 0
jmp .Lcmpend_274
.Lcmp_273:
mov ax, 1
.Lcmpend_274:
test ax, ax
jz .Lelse_271
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _print_uint
add sp, 2
jmp .Lendif_272
.Lelse_271:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 115
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_277
mov ax, 0
jmp .Lcmpend_278
.Lcmp_277:
mov ax, 1
.Lcmpend_278:
test ax, ax
jz .Lelse_275
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _emit_string
add sp, 2
jmp .Lendif_276
.Lelse_275:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 99
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_281
mov ax, 0
jmp .Lcmpend_282
.Lcmp_281:
mov ax, 1
.Lcmpend_282:
test ax, ax
jz .Lelse_279
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
shl ax, 1
mov bx, ax
mov ax, [bp + -12]
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 2
push ax
mov ax, 2
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
push ax
mov ax, 2
mov bx, ax
pop ax
cwd
idiv bx
mov bx, ax
pop ax
shl bx, 1
sub ax, bx
mov bx, ax
mov ax, [bx]
push ax
call _emit_char
add sp, 2
jmp .Lendif_280
.Lelse_279:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_285
mov ax, 0
jmp .Lcmpend_286
.Lcmp_285:
mov ax, 1
.Lcmpend_286:
test ax, ax
jz .Lelse_283
mov ax, 37
push ax
call _emit_char
add sp, 2
jmp .Lendif_284
.Lelse_283:
.Lendif_284:
.Lendif_280:
.Lendif_276:
.Lendif_272:
.Lendif_264:
jmp .Lendif_260
.Lelse_259:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _emit_char
add sp, 2
.Lendif_260:
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
jmp .Lwhile_257
.Lwhileend_258:
mov ax, 0
jmp .fprintf_ret
.fprintf_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
puts:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; `stderr` and `stdout` are token symbols in this minimal runtime —
; fprintf ignores them anyway.
; --- puts ---
.Lwhile_287:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_288
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
call _putchar
add sp, 2
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_287
.Lwhileend_288:
mov ax, 10
push ax
call _putchar
add sp, 2
mov ax, 0
jmp .puts_ret
.puts_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
putchar:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- putchar ---
mov ax, [bp + 4]
push ax
call _putchar
add sp, 2
mov ax, [bp + 4]
jmp .putchar_ret
.putchar_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
getchar:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- getchar ---
call _getchar
jmp .getchar_ret
.getchar_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
scanf:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 10
; Minimal scanf supporting a single "%Ns" or "%s" specifier.
; This is intentionally tiny: it reads a word into the provided buffer
; using the low-level `_getchar` helper. Returns the number of items
; successfully read (0 or 1).
mov ax, 0
mov [bp + -12], ax
mov ax, [bp + 4]
mov [bp + -14], ax
; Find %% and parse optional width
.Lwhile_289:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lscend_291
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_292
mov ax, 0
jmp .Lcmpend_293
.Lcmp_292:
mov ax, 1
.Lcmpend_293:
test ax, ax
jnz .Lsctrue_294
mov ax, 0
jmp .Lscend_291
.Lsctrue_294:
mov ax, 1
.Lscend_291:
test ax, ax
jz .Lwhileend_290
mov ax, [bp + -14]
push ax
inc ax
mov [bp + -14], ax
pop ax
jmp .Lwhile_289
.Lwhileend_290:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 37
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_297
mov ax, 0
jmp .Lcmpend_298
.Lcmp_297:
mov ax, 1
.Lcmpend_298:
test ax, ax
jz .Lelse_295
mov ax, 0
jmp .scanf_ret
jmp .Lendif_296
.Lelse_295:
.Lendif_296:
mov ax, [bp + -14]
push ax
inc ax
mov [bp + -14], ax
pop ax
.Lwhile_299:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
cmp ax, bx
jge .Lcmp_302
mov ax, 0
jmp .Lcmpend_303
.Lcmp_302:
mov ax, 1
.Lcmpend_303:
test ax, ax
jz .Lscend_301
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 57
mov bx, ax
pop ax
cmp ax, bx
jle .Lcmp_304
mov ax, 0
jmp .Lcmpend_305
.Lcmp_304:
mov ax, 1
.Lcmpend_305:
test ax, ax
jnz .Lsctrue_306
mov ax, 0
jmp .Lscend_301
.Lsctrue_306:
mov ax, 1
.Lscend_301:
test ax, ax
jz .Lwhileend_300
mov ax, [bp + -12]
push ax
mov ax, 10
mov bx, ax
pop ax
imul bx
push ax
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
sub ax, bx
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -14]
push ax
inc ax
mov [bp + -14], ax
pop ax
jmp .Lwhile_299
.Lwhileend_300:
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 115
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_309
mov ax, 0
jmp .Lcmpend_310
.Lcmp_309:
mov ax, 1
.Lcmpend_310:
test ax, ax
jz .Lelse_307
mov ax, 0
jmp .scanf_ret
jmp .Lendif_308
.Lelse_307:
.Lendif_308:
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_313
mov ax, 0
jmp .Lcmpend_314
.Lcmp_313:
mov ax, 1
.Lcmpend_314:
test ax, ax
jz .Lelse_311
mov ax, 1024
mov [bp + -12], ax
jmp .Lendif_312
.Lelse_311:
.Lendif_312:
; Skip leading whitespace
.Ldo_315:
call _getchar
mov [bp + -16], ax
mov ax, [bp + -16]
push ax
mov ax, 32
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_320
mov ax, 0
jmp .Lcmpend_321
.Lcmp_320:
mov ax, 1
.Lcmpend_321:
test ax, ax
jnz .Lsctrue_322
mov ax, [bp + -16]
push ax
mov ax, 10
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_323
mov ax, 0
jmp .Lcmpend_324
.Lcmp_323:
mov ax, 1
.Lcmpend_324:
test ax, ax
jnz .Lsctrue_322
mov ax, 0
jmp .Lscend_319
.Lsctrue_322:
mov ax, 1
.Lscend_319:
test ax, ax
jnz .Lsctrue_325
mov ax, [bp + -16]
push ax
mov ax, 9
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_326
mov ax, 0
jmp .Lcmpend_327
.Lcmp_326:
mov ax, 1
.Lcmpend_327:
test ax, ax
jnz .Lsctrue_325
mov ax, 0
jmp .Lscend_318
.Lsctrue_325:
mov ax, 1
.Lscend_318:
test ax, ax
jnz .Lsctrue_328
mov ax, [bp + -16]
push ax
mov ax, 13
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_329
mov ax, 0
jmp .Lcmpend_330
.Lcmp_329:
mov ax, 1
.Lcmpend_330:
test ax, ax
jnz .Lsctrue_328
mov ax, 0
jmp .Lscend_317
.Lsctrue_328:
mov ax, 1
.Lscend_317:
test ax, ax
jnz .Ldo_315
.Ldoend_316:
; leave room for NUL
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + -18], ax
mov ax, [bp + 6]
mov [bp + -20], ax
.Lwhile_331:
mov ax, [bp + -18]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_338
mov ax, 0
jmp .Lcmpend_339
.Lcmp_338:
mov ax, 1
.Lcmpend_339:
test ax, ax
jz .Lscend_337
mov ax, [bp + -16]
push ax
mov ax, 32
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_340
mov ax, 0
jmp .Lcmpend_341
.Lcmp_340:
mov ax, 1
.Lcmpend_341:
test ax, ax
jnz .Lsctrue_342
mov ax, 0
jmp .Lscend_337
.Lsctrue_342:
mov ax, 1
.Lscend_337:
test ax, ax
jz .Lscend_336
mov ax, [bp + -16]
push ax
mov ax, 10
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_343
mov ax, 0
jmp .Lcmpend_344
.Lcmp_343:
mov ax, 1
.Lcmpend_344:
test ax, ax
jnz .Lsctrue_345
mov ax, 0
jmp .Lscend_336
.Lsctrue_345:
mov ax, 1
.Lscend_336:
test ax, ax
jz .Lscend_335
mov ax, [bp + -16]
push ax
mov ax, 9
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_346
mov ax, 0
jmp .Lcmpend_347
.Lcmp_346:
mov ax, 1
.Lcmpend_347:
test ax, ax
jnz .Lsctrue_348
mov ax, 0
jmp .Lscend_335
.Lsctrue_348:
mov ax, 1
.Lscend_335:
test ax, ax
jz .Lscend_334
mov ax, [bp + -16]
push ax
mov ax, 13
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_349
mov ax, 0
jmp .Lcmpend_350
.Lcmp_349:
mov ax, 1
.Lcmpend_350:
test ax, ax
jnz .Lsctrue_351
mov ax, 0
jmp .Lscend_334
.Lsctrue_351:
mov ax, 1
.Lscend_334:
test ax, ax
jz .Lscend_333
mov ax, [bp + -16]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_352
mov ax, 0
jmp .Lcmpend_353
.Lcmp_352:
mov ax, 1
.Lcmpend_353:
test ax, ax
jnz .Lsctrue_354
mov ax, 0
jmp .Lscend_333
.Lsctrue_354:
mov ax, 1
.Lscend_333:
test ax, ax
jz .Lwhileend_332
mov ax, [bp + -16]
push ax
mov ax, [bp + -20]
push ax
inc ax
mov [bp + -20], ax
pop ax
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -18]
push ax
dec ax
mov [bp + -18], ax
pop ax
call _getchar
mov [bp + -16], ax
jmp .Lwhile_331
.Lwhileend_332:
mov ax, 0
push ax
mov ax, [bp + -20]
mov bx, ax
pop ax
mov [bx], al
mov ax, 1
jmp .scanf_ret
.scanf_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret

; --- Data Segment ---
section .data

stderr: dw 0
stdout: dw 0
stdin: dw 0

; --- BSS Segment ---
section .bss

_spr_out: resw 1
_spr_n: resw 1

group DGROUP data bss