; === Generated by pyc ===

[bits 16]


; --- Exported symbols ---
global _heap
global _heap_pos
global _rand_seed
global atof
global atoi
global atol
global calloc
global exit
global free
global malloc
global rand
global realloc
global srand

; --- Imported symbols ---
extern __mul32
extern __ret64_hi
extern _exit

; --- Code Segment ---
section .text

exit:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; stdlib.c - Standard library for pyc
; Added typedef for size_t
; abs is a macro to avoid conflict with NASM reserved word 'abs'
; DOS I/O helper
; --- exit ---
mov ax, [bp + 4]
push ax
call _exit
add sp, 2
.exit_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
atoi:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 4
; --- atoi ---
mov ax, 0
mov [bp + -12], ax
mov ax, 0
mov [bp + -14], ax
.Lwhile_1:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 32
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_4
mov ax, 0
jmp .Lcmpend_5
.Lcmp_4:
mov ax, 1
.Lcmpend_5:
test ax, ax
jnz .Lsctrue_6
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 9
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_7
mov ax, 0
jmp .Lcmpend_8
.Lcmp_7:
mov ax, 1
.Lcmpend_8:
test ax, ax
jnz .Lsctrue_6
mov ax, 0
jmp .Lscend_3
.Lsctrue_6:
mov ax, 1
.Lscend_3:
test ax, ax
jz .Lwhileend_2
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_1
.Lwhileend_2:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 45
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_11
mov ax, 0
jmp .Lcmpend_12
.Lcmp_11:
mov ax, 1
.Lcmpend_12:
test ax, ax
jz .Lelse_9
mov ax, 1
mov [bp + -14], ax
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lendif_10
.Lelse_9:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 43
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_15
mov ax, 0
jmp .Lcmpend_16
.Lcmp_15:
mov ax, 1
.Lcmpend_16:
test ax, ax
jz .Lelse_13
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lendif_14
.Lelse_13:
.Lendif_14:
.Lendif_10:
.Lwhile_17:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
cmp ax, bx
jge .Lcmp_20
mov ax, 0
jmp .Lcmpend_21
.Lcmp_20:
mov ax, 1
.Lcmpend_21:
test ax, ax
jz .Lscend_19
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 57
mov bx, ax
pop ax
cmp ax, bx
jle .Lcmp_22
mov ax, 0
jmp .Lcmpend_23
.Lcmp_22:
mov ax, 1
.Lcmpend_23:
test ax, ax
jnz .Lsctrue_24
mov ax, 0
jmp .Lscend_19
.Lsctrue_24:
mov ax, 1
.Lscend_19:
test ax, ax
jz .Lwhileend_18
mov ax, [bp + -12]
push ax
mov ax, 10
mov bx, ax
pop ax
imul bx
push ax
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, 48
mov bx, ax
pop ax
sub ax, bx
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_17
.Lwhileend_18:
mov ax, [bp + -14]
test ax, ax
jz .Lelse_25
mov ax, [bp + -12]
neg ax
mov [bp + -12], ax
jmp .Lendif_26
.Lelse_25:
.Lendif_26:
mov ax, [bp + -12]
jmp .atoi_ret
.atoi_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
atol:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- atol ---
mov ax, [bp + 4]
push ax
call atoi
add sp, 2
jmp .atol_ret
.atol_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
malloc:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 4
; --- malloc: bump-pointer allocator over a fixed BSS heap. ---
; Heap layout: `_heap` is a 16 KB byte array in BSS; `_heap_pos`
; is the index of the next free byte.  Allocations align up to 2
; bytes (matching the natural word alignment for the 16-bit target).
; This is intentionally simple — no coalescing, no reuse — but lets
; programs that allocate-and-forget run correctly.
; Align request up to 2 bytes.
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 1
not ax
mov bx, ax
pop ax
and ax, bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jle .Lcmp_29
mov ax, 0
jmp .Lcmpend_30
.Lcmp_29:
mov ax, 1
.Lcmpend_30:
test ax, ax
jz .Lelse_27
mov ax, 0
jmp .malloc_ret
jmp .Lendif_28
.Lelse_27:
.Lendif_28:
mov ax, [_heap_pos]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
add ax, bx
push ax
mov ax, 16384
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_33
mov ax, 0
jmp .Lcmpend_34
.Lcmp_33:
mov ax, 1
.Lcmpend_34:
test ax, ax
jz .Lelse_31
mov ax, 0
jmp .malloc_ret
jmp .Lendif_32
.Lelse_31:
.Lendif_32:
mov ax, _heap
push ax
mov ax, [_heap_pos]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
mov al, [bx]
xor ah, ah
mov ax, _heap
push ax
mov ax, [_heap_pos]
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, [_heap_pos]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
add ax, bx
mov [_heap_pos], ax
mov ax, [bp + -14]
jmp .malloc_ret
.malloc_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
free:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
.free_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
calloc:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 6
; --- free (no-op for bump allocator) ---
; --- calloc: malloc + zero-fill ---
mov ax, [bp + 4]
push ax
mov ax, [bp + 6]
mov bx, ax
pop ax
imul bx
mov [bp + -12], ax
mov ax, [bp + -12]
push ax
call malloc
add sp, 2
mov [bp + -14], ax
mov ax, [bp + -14]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_37
mov ax, 0
jmp .Lcmpend_38
.Lcmp_37:
mov ax, 1
.Lcmpend_38:
test ax, ax
jz .Lelse_35
mov ax, 0
jmp .calloc_ret
jmp .Lendif_36
.Lelse_35:
.Lendif_36:
mov ax, 0
mov [bp + -16], ax
.Lfor_39:
mov ax, [bp + -16]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_42
mov ax, 0
jmp .Lcmpend_43
.Lcmp_42:
mov ax, 1
.Lcmpend_43:
test ax, ax
jz .Lforend_41
mov ax, 0
push ax
mov ax, [bp + -14]
push ax
mov ax, [bp + -16]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
.Lforcontinue_40:
mov ax, [bp + -16]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -16], ax
jmp .Lfor_39
.Lforend_41:
mov ax, [bp + -14]
jmp .calloc_ret
.calloc_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
realloc:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 6
; --- realloc: allocate fresh, copy bytes, leak old (bump alloc) ---
mov ax, [bp + 6]
push ax
call malloc
add sp, 2
mov [bp + -12], ax
mov ax, [bp + 4]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_47
mov ax, 0
jmp .Lcmpend_48
.Lcmp_47:
mov ax, 1
.Lcmpend_48:
test ax, ax
jnz .Lsctrue_49
mov ax, [bp + -12]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_50
mov ax, 0
jmp .Lcmpend_51
.Lcmp_50:
mov ax, 1
.Lcmpend_51:
test ax, ax
jnz .Lsctrue_49
mov ax, 0
jmp .Lscend_46
.Lsctrue_49:
mov ax, 1
.Lscend_46:
test ax, ax
jz .Lelse_44
mov ax, [bp + -12]
jmp .realloc_ret
jmp .Lendif_45
.Lelse_44:
.Lendif_45:
; We don't know the old size; copy `size` bytes which is the
; caller's promise that's at least the old size.
mov ax, [bp + 4]
mov [bp + -14], ax
mov ax, 0
mov [bp + -16], ax
.Lfor_52:
mov ax, [bp + -16]
push ax
mov ax, [bp + 6]
mov bx, ax
pop ax
cmp ax, bx
jl .Lcmp_55
mov ax, 0
jmp .Lcmpend_56
.Lcmp_55:
mov ax, 1
.Lcmpend_56:
test ax, ax
jz .Lforend_54
mov ax, [bp + -14]
push ax
mov ax, [bp + -16]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + -12]
push ax
mov ax, [bp + -16]
mov bx, ax
pop ax
add ax, bx
mov bx, ax
pop ax
mov [bx], al
.Lforcontinue_53:
mov ax, [bp + -16]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -16], ax
jmp .Lfor_52
.Lforend_54:
mov ax, [bp + -12]
jmp .realloc_ret
.realloc_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
atof:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- atof (stub - returns 0.0) ---
; No FPU emulation; declared so source compiles and links.
mov ax, 0
cwd
mov bx, dx
mov cx, dx
mov [__ret64_hi], bx
mov [__ret64_hi + 2], cx
jmp .atof_ret
.atof_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
srand:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; `abs` collides with a NASM reserved word; it is provided as a macro in
; <stdlib.h>: #define ((x) < 0 ? -(x) : (x)) ((x)<0?-(x):(x))
; --- rand / srand: LCG, C stdlib-compatible parameters ---
; Seed must be 32-bit so that (seed >> 16) produces a non-zero result.
; unsigned int is 16-bit in pyc; use unsigned long (32-bit) for the seed.
mov ax, [bp + 4]
xor dx, dx
mov [_rand_seed], ax
mov [_rand_seed + 2], dx
.srand_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
rand:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
mov ax, 20077
mov dx, 16838
push dx
push ax
mov ax, [_rand_seed]
mov dx, [_rand_seed + 2]
push dx
push ax
call __mul32
add sp, 8
push dx
push ax
mov ax, 12345
mov dx, 0
mov bx, ax
mov cx, dx
pop ax
pop dx
add ax, bx
adc dx, cx
mov [_rand_seed], ax
mov [_rand_seed + 2], dx
mov ax, [_rand_seed]
mov dx, [_rand_seed + 2]
push dx
push ax
mov ax, 16
cwd
mov bx, ax
mov cx, dx
pop ax
pop dx
mov cl, bl
cmp cl, 32
jge .Lsh32h_59
cmp cl, 16
jge .Lsh32b_58
.Lsh32l_60:
test cl, cl
jz .Lsh32d_57
sar dx, 1
rcr ax, 1
dec cl
jmp .Lsh32l_60
.Lsh32b_58:
sub cl, 16
sar dx, cl
mov ax, dx
sar dx, 15
jmp .Lsh32d_57
.Lsh32h_59:
sar dx, 15
mov ax, dx
.Lsh32d_57:
push dx
push ax
mov ax, 32767
cwd
mov bx, ax
mov cx, dx
pop ax
pop dx
and ax, bx
and dx, cx
jmp .rand_ret
.rand_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret

; --- Data Segment ---
section .data

_heap_pos: dw 0
_rand_seed: dw 1, 0

; --- BSS Segment ---
section .bss

_heap: resw 8192

group DGROUP data bss