; === Generated by pyc ===

[bits 16]


; --- Exported symbols ---
global memcpy
global memset
global strcat
global strcmp
global strcpy
global strlen
global strncmp
global strncpy

; --- Code Segment ---
section .text

strlen:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 2
; string.c - String functions for pyc
; --- strlen ---
mov ax, 0
mov [bp + -12], ax
.Lwhile_1:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_2
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
jmp .Lwhile_1
.Lwhileend_2:
mov ax, [bp + -12]
jmp .strlen_ret
.strlen_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
strcpy:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 2
; --- strcpy ---
mov ax, [bp + 4]
mov [bp + -12], ax
.Lwhile_3:
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_4
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 6], ax
jmp .Lwhile_3
.Lwhileend_4:
mov ax, 0
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + 4]
jmp .strcpy_ret
.strcpy_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
strcmp:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- strcmp ---
.Lwhile_5:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lscend_7
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jnz .Lsctrue_8
mov ax, 0
jmp .Lscend_7
.Lsctrue_8:
mov ax, 1
.Lscend_7:
test ax, ax
jz .Lwhileend_6
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_11
mov ax, 0
jmp .Lcmpend_12
.Lcmp_11:
mov ax, 1
.Lcmpend_12:
test ax, ax
jz .Lelse_9
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
sub ax, bx
jmp .strcmp_ret
jmp .Lendif_10
.Lelse_9:
.Lendif_10:
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
mov ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 6], ax
jmp .Lwhile_5
.Lwhileend_6:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
sub ax, bx
jmp .strcmp_ret
.strcmp_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
memcpy:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 4
; --- memcpy ---
mov ax, [bp + 4]
mov [bp + -12], ax
mov ax, [bp + 6]
mov [bp + -14], ax
.Lwhile_13:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_15
mov ax, 0
jmp .Lcmpend_16
.Lcmp_15:
mov ax, 1
.Lcmpend_16:
test ax, ax
jz .Lwhileend_14
mov ax, [bp + -14]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + -14]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -14], ax
mov ax, [bp + 8]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + 8], ax
jmp .Lwhile_13
.Lwhileend_14:
mov ax, [bp + 4]
jmp .memcpy_ret
.memcpy_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
memset:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 2
; --- memset ---
mov ax, [bp + 4]
mov [bp + -12], ax
.Lwhile_17:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_19
mov ax, 0
jmp .Lcmpend_20
.Lcmp_19:
mov ax, 1
.Lcmpend_20:
test ax, ax
jz .Lwhileend_18
mov ax, [bp + 6]
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 8]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + 8], ax
jmp .Lwhile_17
.Lwhileend_18:
mov ax, [bp + 4]
jmp .memset_ret
.memset_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
strncpy:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 2
; --- strncpy: copy at most n bytes, zero-pad remainder ---
mov ax, [bp + 4]
mov [bp + -12], ax
.Lwhile_21:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_24
mov ax, 0
jmp .Lcmpend_25
.Lcmp_24:
mov ax, 1
.Lcmpend_25:
test ax, ax
jz .Lscend_23
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jnz .Lsctrue_26
mov ax, 0
jmp .Lscend_23
.Lsctrue_26:
mov ax, 1
.Lscend_23:
test ax, ax
jz .Lwhileend_22
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 6], ax
mov ax, [bp + 8]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + 8], ax
jmp .Lwhile_21
.Lwhileend_22:
.Lwhile_27:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_29
mov ax, 0
jmp .Lcmpend_30
.Lcmp_29:
mov ax, 1
.Lcmpend_30:
test ax, ax
jz .Lwhileend_28
mov ax, 0
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 8]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + 8], ax
jmp .Lwhile_27
.Lwhileend_28:
mov ax, [bp + 4]
jmp .strncpy_ret
.strncpy_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
strcat:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
sub sp, 2
; --- strcat: append src to dest ---
mov ax, [bp + 4]
mov [bp + -12], ax
.Lwhile_31:
mov ax, [bp + -12]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_32
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
jmp .Lwhile_31
.Lwhileend_32:
.Lwhile_33:
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jz .Lwhileend_34
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + -12]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + -12], ax
mov ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 6], ax
jmp .Lwhile_33
.Lwhileend_34:
mov ax, 0
push ax
mov ax, [bp + -12]
mov bx, ax
pop ax
mov [bx], al
mov ax, [bp + 4]
jmp .strcat_ret
.strcat_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret
strncmp:
push bp
mov bp, sp
push bx
push cx
push dx
push si
push di
; no locals
; --- strncmp: compare at most n chars ---
.Lwhile_35:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
jg .Lcmp_39
mov ax, 0
jmp .Lcmpend_40
.Lcmp_39:
mov ax, 1
.Lcmpend_40:
test ax, ax
jz .Lscend_38
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jnz .Lsctrue_41
mov ax, 0
jmp .Lscend_38
.Lsctrue_41:
mov ax, 1
.Lscend_38:
test ax, ax
jz .Lscend_37
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
test ax, ax
jnz .Lsctrue_42
mov ax, 0
jmp .Lscend_37
.Lsctrue_42:
mov ax, 1
.Lscend_37:
test ax, ax
jz .Lwhileend_36
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
cmp ax, bx
jne .Lcmp_45
mov ax, 0
jmp .Lcmpend_46
.Lcmp_45:
mov ax, 1
.Lcmpend_46:
test ax, ax
jz .Lelse_43
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
sub ax, bx
jmp .strncmp_ret
jmp .Lendif_44
.Lelse_43:
.Lendif_44:
mov ax, [bp + 4]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 4], ax
mov ax, [bp + 6]
push ax
mov ax, 1
mov bx, ax
pop ax
add ax, bx
mov [bp + 6], ax
mov ax, [bp + 8]
push ax
mov ax, 1
mov bx, ax
pop ax
sub ax, bx
mov [bp + 8], ax
jmp .Lwhile_35
.Lwhileend_36:
mov ax, [bp + 8]
push ax
mov ax, 0
mov bx, ax
pop ax
cmp ax, bx
je .Lcmp_49
mov ax, 0
jmp .Lcmpend_50
.Lcmp_49:
mov ax, 1
.Lcmpend_50:
test ax, ax
jz .Lelse_47
mov ax, 0
jmp .strncmp_ret
jmp .Lendif_48
.Lelse_47:
.Lendif_48:
mov ax, [bp + 4]
mov bx, ax
mov al, [bx]
xor ah, ah
push ax
mov ax, [bp + 6]
mov bx, ax
mov al, [bx]
xor ah, ah
mov bx, ax
pop ax
sub ax, bx
jmp .strncmp_ret
.strncmp_ret:
mov di, [bp - 10]
mov si, [bp - 8]
mov cx, [bp - 4]
mov bx, [bp - 2]
mov sp, bp
pop bp
ret